openapi: 3.0.0
info:
  version: 1.4.0
  title: Managed Prescence Server (MPS) API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    This section is a reference to the MPS API methods available in the Open AMT Cloud Toolkit, and to some commands it provides. 
    Please note when running behind the Kong API proxy the following prefixes must be prepended:
    * `/mps/login` for `/api/v1/authorize`

    * `/mps/ws` for websocket routes

    * `/mps` for all other routes

    Authorize API Example:
    * Direct connection to MPS: `{{protocol}}://{{host}}/api/v1/authorize`

    * Connection to MPS through Kong: `{{protocol}}://{{host}}/mps/login/api/v1/authorize`

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/rbheopenamt/mps/1.3.0
security:
  - BearerAuth: []
paths:
  /api/v1/authorize:
    post:
      description: Generates a JWT token that can be used for authentication to both RPS and MPS APIs
      tags:
        - Auth
      requestBody:
        description: Payload with username and password
        required: true
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        401:
          description: 'Incorrect Username and/or Password'
        200:
          description: 'success'
          content:
            application/json:
              schema:
                properties:
                  token:
                    type: string
  /api/v1/amt/log/audit/{guid}:
    get:
      description: Returns Intel® AMT Audit Log data in blocks of 10 records for a specified guid.  Reference [AMT SDK](https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm?turl=WordDocuments%2Freadingtheauditlog.htm) for definition of property return codes
      tags:
        - AMT
      parameters:
      - name: guid
        in: path
        description: GUID of device
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      - name: startIndex
        in: query
        description: number of items to skip
        example: "startIndex=0"
        schema:
          type: integer
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditLogResponse'
  /api/v1/amt/log/event/{guid}:
    get:
      description: Return sensor and hardware event data from the Intel® AMT event log.  Reference [AMT SDK](https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm?turl=HTMLDocuments%2FWS-Management_Class_Reference%2FAMT_EventLogEntry.htm) for definition of property return codes
      tags:
        - AMT
      parameters:
      - name: guid
        in: path
        description: GUID of device
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      # - name: startDate
      #   in: query
      #   description: Start date of log to retrieve
      #   required: true
      #   example: "2019-04-11"
      #   schema:
      #     type: string
      # - name: endDate
      #   in: query
      #   description: End date of log to retrieve
      #   required: true
      #   example: "2019-04-18"
      #   schema:
      #     type: string
      # - name: logsPerPage
      #   in: query
      #   description: Number of logs to return for this page
      #   required: true
      #   example: 10
      #   schema:
      #     type: number
      # - name: page
      #   in: query
      #   description: Page of logs to retrieve
      #   required: true
      #   example: 5
      #   schema:
      #     type: number
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventLogResponse'
  /api/v1/amt/version/{guid}:
    get:
      description: Retrieves hardware version information for Intel® AMT and current activation state
      tags:
        - AMT
      parameters:
      - name: guid
        in: path
        description: GUID of device
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResponse'
  /api/v1/amt/generalSettings/{guid}:
    get:
      description: Retrieve the Intel® AMT general settings
      tags:
        - AMT
      parameters:
      - name: guid
        in: path
        description: GUID of device
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralSettingsResponse'
  /api/v1/amt/hardwareInfo/{guid}:
    get:
      description: Retrieve hardware information such as processor or storage
      tags:
        - AMT
      parameters:
      - name: guid
        in: path
        description: GUID of device
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HardwareInfoResponse'
  /api/v1/amt/features/{guid}:
    post:
      description: Enable/Disable Intel® AMT User Consent, Redirection, KVM, SOL, and IDE-R features
      tags:
        - AMT
      parameters:
      - name: guid
        in: path
        description: GUID of device
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      requestBody:
        description: Payload to set AMT Features
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetAMTFeaturesRequest'
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetAMTFeaturesResponse'
    get:
      description: Retrieves the current Intel® AMT Enable/Disable state for User Consent, Redirection, KVM, SOL, and IDE-R
      tags:
        - AMT
      parameters:
      - name: guid
        in: path
        description: GUID of device
        required: true
        schema:
          type: string
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAMTFeaturesResponse'
  /api/v1/amt/power/state/{guid}:
    get:
      description: |
        Retrieve current power state of Intel® AMT device, returns a number that maps to a device power state. 
        Possible power state values: 
        * 2 = On - corresponding to ACPI state G0 or S0 or D0 
        * 3 = Sleep - Light, corresponding to ACPI state G1, S1/S2, or D1 
        * 4 = Sleep - Deep, corresponding to ACPI state G1, S3, or D2 
        * 6 = Off - Hard, corresponding to ACPI state G3, S5, or D3 
        * 7 = Hibernate (Off - Soft), corresponding to ACPI state S4, where the state of the managed element is preserved and will be recovered upon powering on 
        * 8 = Off - Soft, corresponding to ACPI state G2, S5, or D3 
        * 9 = Power Cycle (Off-Hard), corresponds to the managed element reaching the ACPI state G3 followed by ACPI state S0 
        * 13 = Off - Hard Graceful, equivalent to Off Hard but preceded by a request to the managed element to perform an orderly shutdown.      
      tags:
        - AMT
      parameters:
      - name: guid
        in: path
        description: GUID of device
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PowerStateResponse'
  /api/v1/amt/power/capabilities/{guid}:
    get:
      description: View what OOB power actions are available for that device
      tags:
        - AMT
      parameters:
      - name: guid
        in: path
        description: GUID of device
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PowerCapabilitiesResponse'
  /api/v1/amt/power/action/{guid}:
    post:
      description: Perform an OOB power action.  Execute a GET Power/Capabilities/{guid} call first to get the list of available power actions.
      tags:
        - AMT
      parameters:
      - name: guid
        in: path
        description: GUID of device
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      requestBody:
        description: Payload to perform a power action
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PowerActionRequest'
      responses:
        200:
          description: 'successful operation'
          content:
           application/json:
             schema:
               $ref: '#/components/schemas/PowerActionResponse'
  /api/v1/devices:
    get:
      description: Lists all devices known to MPS
      tags:
        - Devices
      parameters:
      - name: tags
        in: query
        description: Comma-delimited list of tags to query for
        example: 'tags=NUC,Store #123'
        required: false
        schema:
          type: string
      - name: status
        in: query
        description: Specify '0' to query for disconnected devices or specify '1' for connected devices. To return all devices, omit this query parameter.
        example: 'status=1'
        required: false
        schema:
          type: integer
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
        500:
          description: 'Internal server error'
    post:
      description: Adds a new device to MPS
      tags:
        - Devices
      requestBody:
        description: Payload to add AMT device to MPS
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddDevice'
      responses:
        200:
          description: 'Successful operation'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AddDevice'
        500:
          description: 'Internal server error'
    patch:
      description: Edit a single device in the MPS
      tags:
        - Devices
      requestBody:
        description: Payload to edit AMT device in MPS
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddDevice'
      responses:
        200:
          description: 'Successful operation'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AddDevice'
        500:
          description: 'Internal server error'
  /api/v1/devices/stats:
    get:
      description: Retrieve the current count of all registered, connected, and disconnected devices
      tags:
        - Devices
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'
  /api/v1/devices/{guid}:
    get:
      description: Retrieves the device with a specific GUID and all device information from the database 
      tags:
        - Devices
      parameters:
      - name: guid
        in: path
        description: GUID of device to return
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      responses:
        404:
          description: 'Device does not exist'
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
  /api/v1/devices/disconnect/{guid}:
    delete:
      description: Forces a specified device to disconnect from the MPS. Device will reconnect again if it is able.
      tags:
        - Devices
      parameters:
      - name: guid
        in: path
        description: GUID of device to return
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      responses:
        404:
          description: 'Device does not exist'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisconnectErrorResponse'
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisconnectResponse'
  /api/v1/metadata:
    get:
      description: Retrieves all devices and metadata information from the database
      tags:
        - Metadata
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Metadata'
    post:
      description: Adds a new devices and metadata information to the database.
      tags:
        - Metadata
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Metadata'
      responses:
        201:
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metadata'
    patch:
      description: Edits a device's metadata information in the database.
      tags:
        - Metadata
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Metadata'
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metadata'
  /api/v1/metadata/{guid}:
    get:
      description: Retrieves the device with a specific GUID and all metadata information from the database
      tags:
        - Metadata
      parameters:
      - name: guid
        in: path
        description: GUID of device to return
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      responses:
        404:
          description: 'Metadata for device does not exist'
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metadata'
    delete:
      description: Removes the device with a specific GUID from the database
      tags:
        - Metadata
      parameters:
      - name: guid
        in: path
        description: GUID of device to return
        example: 123e4567-e89b-12d3-a456-426614174000
        required: true
        schema:
          type: string
      responses:
        204:
          description: 'no content'
  /api/v1/metadata/tags:
    get:
      description: Returns a list of unique tags across all devices in MPS
      tags:
        - Metadata
      responses:
        200:
          description: 'successful operation'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SetAMTFeaturesRequest:
      title: SetAMTFeaturesRequest
      properties:
        userConsent:
          type: string
          enum: 
            - kvm
            - all
            - none
        redirection:
          type: boolean
        enableSOL:
          type: boolean
        enableIDER:
          type: boolean
        enableKVM:
          type: boolean
    DisconnectResponse:
      title: DisconnectResponse
      example:
        success: 200
        description: "CIRA connection disconnected : 038d0240-045c-05f4-7706-980700080009"
      properties:
        success:
          description: HTTP returncode
          type: integer
        description:
          description: server response message containing guid
          type: string
    DisconnectErrorResponse:
      title: DisconnectErrorResponse
      example:
        status: 404
        error: "Device not found/connected. Please connect again using CIRA."
        errorDescription: "guid : 038d0240-045c-05f4-7706-980700080009"
      properties:
        success:
          description: HTTP returncode
          type: integer
        error:
          description: server error message
          type: string
        errorDescription:
          description: contains device guid
          type: string
    DeleteResponse:
      title: DeleteResponse
      example:
        success: 204
      properties:
        success:
          description: HTTP returncode
          type: integer
    DeleteErrorResponse:
      title: DeleteErrorResponse
      example:
        status: 404
        error: "NOT FOUND"
        errorDescription: "Device ID 038d0240-045c-05f4-7706-980700080009 not found"
      properties:
        success:
          description: HTTP returncode
          type: integer
        error:
          description: server error message
          type: string
        errorDescription:
          description: contains device guid
          type: string
    AuditLogResponse:
      title: AuditLogResponse
      example:
          totalCnt: 2
          records:
          - auditAppID: 18
            eventID: 10
            initiatorType: 0
            auditApp: Redirection Manager
            event: KVM Enabled
            initiator: admin
            time: "2003-12-29T05:46:37.000Z"
            mcLocationType: 0
            netAddress: "1.2.3.4"
            ex: ""
            exStr: null
          - auditAppID: 16
            eventID: 19
            initiatorType: 0
            auditApp: Security Admin
            event: Unprovisioning Started
            initiator: admin
            time: "2017-12-21T17:30:39.000Z"
            mcLocationType: 1
            netAddress: ::1
            ex:
              type: Buffer
            exStr: Remote WSMAN
      properties:
          auditAppID:
            type: integer
          eventID: 
            type: integer
          initiatorType:
            type: integer
          auditApp: 
            type: string
          event: 
            type: string
          initiator: 
            type: string
          time: 
            type: string
          mcLocationType:
            type: integer
          netAddress: 
            type: string 
          ex:
            type: object
            properties:
              type: 
                type: string
              data:
                type: array
                items:
                  type: integer
          exStr: 
            type: string
    EventLogResponse:
      title: EventLogResponse
      example:
        - deviceAddress: 255
          eventSensorType: 15
          eventType: 111
          eventOffset: 2
          eventSourceType: 104
          eventSeverity: 1
          sensorNumber: 255
          entity: 34
          entityInstance: 0
          eventData:
          - 64
          - 6
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          time: '2019-04-11T17:57:40.000Z'
          entityStr: BIOS
          desc: USB resource configuration
      properties:
        deviceAddress:
          type: integer
        eventSensorType:
          type: integer
        eventType:
          type: integer
        eventOffset:
          type: integer
        eventSourceType:
          type: integer
        eventSeverity:
          type: integer
        sensorNumber:
          type: integer
        entity: 
          type: integer
        entityInstance:
          type: integer
        eventData:
          type: array
          items:
            type: integer
        time: 
          type: string
        entityStr:
          type: string
        desc:
          type: string
    GeneralSettingsResponse:
      title: GeneralSettingsResponse
      example:
        Header:
          To: http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous
          RelatesTo: "1"
          Action: http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse
          MessageID: uuid:00000000-8086-8086-8086-000000000699
          ResourceURI: http://intel.com/wbem/wscim/1/amt-schema/1/AMT_GeneralSettings
          Method: AMT_GeneralSettings
        Body:
          amtNetworkEnabled: 1
          ddnsPeriodicUpdateInterval: 1440
          ddnsTTL: 900
          ddnsUpdateByDHCPServerEnabled: true
          ddnsUpdateEnabled: false
          dhcpv6ConfigurationTimeout: 0
          digestRealm: Digest:A4070000000000000000000000000000
          elementName: 'Intel(r) AMT: General Settings'
          idleWakeTimeout: 65535
          instanceID: 'Intel(r) AMT: General Settings'
          networkInterfaceEnabled: true
          pingResponseEnabled: true
          powerSource: 0
          preferredAddressFamily: 0
          presenceNotificationInterval: 0
          privacyLevel: 0
          rmcpPingResponseEnabled: true
          sharedFQDN: true
          wsmanOnlyMode: false
      properties:
        Header:
          type: object
          properties:
            To:
              type: string
            RelatesTo:
              type: string
            Action:
              type: string
            MessageID:
              type: string
            ResourceURI:
              type: string
            Method:
              type: string
        Body:
          type: object
          properties:
            amtNetworkEnabled:
              type: integer
            ddnsPeriodicUpdateInterval:
              type: integer
            ddnsTTL:
              type: integer
            ddnsUpdateByDHCPServerEnabled:
              type: boolean
            ddnsUpdateEnabled: 
              type: boolean
            dhcpv6ConfigurationTimeout:
              type: integer
            digestRealm:
              type: string
            elementName:
              type: string
            idleWakeTimeout:
              type: integer
            instanceID:
              type: string
            networkInterfaceEnabled:
              type: boolean
            pingResponseEnabled:
              type: boolean
            powerSource: 
              type: integer
            preferredAddressFamily:
              type: integer
            presenceNotificationInterval:
              type: integer
            privacyLevel:
              type: integer
            rmcpPingResponseEnabled:
              type: boolean
            sharedFQDN:
              type: boolean
            wsmanOnlyMode:
              type: boolean
    GetAMTFeaturesResponse:
      title: GetAMTFeaturesResponse
      properties:
        userConsent:
          type: string
        redirection:
          type: boolean
        KVM:
          type: boolean
        SOL: 
          type: boolean
        IDER: 
          type: boolean
      example: 
        userConsent: kvm
        redirection: false
        KVM: false
        SOL: true
        IDER: true
    HardwareInfoResponse:
      title: HardwareInfoResponse
      properties:
        CIM_ComputerSystemPackage:
          type: object
          properties:
            response:
              type: object
              properties:
                antecedent:
                  type: object
                  properties:
                    address:
                      type: string
                    referenceParameters:
                      type: object
                      properties:
                        resourceURI:
                          type: string
                        selectorSet:
                          type: object
                          properties:
                            selector:
                              type: object
                              properties:
                                value:
                                  type: string
                                '@name': 
                                  type: string
                dependent:
                  type: object
                  properties:
                    address:
                      type: string
                    ReferenceParameters:
                      type: object
                      properties:
                        resourceURI:
                          type: string
                        selectorSet:
                          type: object
                          properties:
                            selector:
                              type: object
                              properties:
                                value:
                                  type: string
                                "@name":
                                  type: string
                platformGUID:
                  type: string
            status:
              type: integer
        CIM_SystemPackaging:
          type: object
          properties:
            responses:
              type: object
              properties:
                antecedent:
                  type: object
                  properties:
                    address:
                      type: string
                    referenceParameters:
                      type: object
                      properties:
                        resourceURI:
                          type: string
                        selectorSet:
                          type: object
                          properties:
                            selector:
                              type: object
                              properties:
                                value:
                                  type: string
                                "@name":
                                  type: string
                dependent:
                  type: object
                  properties:
                    address:
                      type: string
                    referenceParameters:
                      type: object
                      properties:
                        resourceURI:
                          type: string
                        selectorSet:
                          type: object
                          properties:
                            selector:
                              type: object
                              properties:
                                value:
                                  type: string
                                "@name":
                                  type: string
                platformGUID:
                  type: string
            status:
              type: integer
        CIM_Chassis:
          type: object
          properties:
            response:
              type: object
              properties:
                chassisPackageType:
                  type: integer
                creationClassName:
                  type: string
                elementName:
                  type: string
                manufacturer:
                  type: string
                model:
                  type: string
                operationalStatus:
                  type: integer
                packageType:
                  type: integer
                serialNumber:
                  type: string
                tag:
                  type: string
                version:
                  type: string
            responses:
              type: object
              properties:
                Header:
                  type: object
                  properties:
                    To:
                      type: string
                    RelatesTo:
                      type: integer
                    Action:
                      type: string
                    MessageID:
                      type: string
                    ResourceURI:
                      type: string
                    Method:
                      type: string
                Body:
                  type: object
                  properties:
                    ChassisPackageType:
                      type: integer
                    CreationClassName:
                      type: string
                    ElementName:
                      type: string
                    Manufacturer:
                      type: string
                    Model:
                      type: string
                    OperationalStatus:
                      type: integer
                    PackageType:
                      type: integer
                    SerialNumber:
                      type: string
                    Tag:
                      type: string
                    Version:
                      type: string
            status:
              type: integer
        CIM_Chip:
          type: object
          properties:
            responses:
              type: array
              items:
                type: object
                properties:
                  canBeFRUed:
                    type: boolean
                  creationClassName:
                    type: string
                  elementName:
                    type: string
                  manufacturer:
                    type: string
                  operationalStatus:
                    type: integer
                  tag:
                    type: string
                  version:
                    type: string
                  bankLabel: 
                    type: string
                  capacity:
                    type: integer
                  formFactor:
                    type: integer
                  memoryType:
                    type: integer
                  partNumber:
                    type: string
                  serialNumber:
                    type: string
                  speed:
                    type: integer
            status:
              type: integer
        CIM_Card:
          type: object
          properties:
            response:
              type: object
              properties:
                canBeFRUed:
                  type: boolean
                creationClassName:
                  type: string
                elementName: 
                  type: string
                manufacturer: 
                  type: string
                model: 
                  type: string
                operationalStatus:
                  type: integer
                packageType:
                  type: integer
                serialNumber: 
                  type: string
                tag: 
                  type: string
                version:
                  type: string
            responses:
              type: object
              properties:
                Header:
                  type: object
                  properties:
                    To:
                      type: string
                    RelatesTo:
                      type: integer
                    Action:
                      type: string
                    MessageID:
                      type: string
                    ResourceURI:
                      type: string
                    Method:
                      type: string
                Body:
                  type: object
                  properties:
                    canBeFRUed:
                      type: boolean
                    creationClassName:
                      type: string
                    elementName: 
                      type: string
                    manufacturer: 
                      type: string
                    model: 
                      type: string
                    operationalStatus:
                      type: integer
                    packageType:
                      type: integer
                    serialNumber: 
                      type: string
                    tag: 
                      type: string
                    version:
                      type: string
            status:
              type: integer
        CIM_BIOSElement:
          type: object
          properties:
            response:
              type: object
              properties:
                elementName:
                  type: string
                manufacturer:
                  type: string
                name:
                  type: string
                operationalStatus:
                  type: integer
                primaryBIOS:
                  type: boolean
                releaseDate:
                  type: object
                  properties:
                    datetime:
                      type: string
                softwareElementID: 
                  type: string
                softwareElementState:
                  type: integer
                targetOperatingSystem:
                  type: integer
                version: 
                  type: string
            responses:
              type: object
              properties:
                Header:
                  type: object
                  properties:
                    To:
                      type: string
                    RelatesTo:
                      type: integer
                    Action:
                      type: string
                    MessageID:
                      type: string
                    ResourceURI:
                      type: string
                    Method:
                      type: string
                Body:
                  type: object
                  properties:
                    ElementName:
                      type: string
                    Manufacturer:
                      type: string
                    Name:
                      type: string
                    OperationalStatus:
                      type: integer
                    PrimaryBIOS:
                      type: boolean
                    ReleaseDate:
                      type: object
                      properties:
                        Datetime:
                          type: string
                    SoftwareElementID: 
                      type: string
                    SoftwareElementState:
                      type: integer
                    TargetOperatingSystem:
                      type: integer
                    Version: 
                      type: string
            status:
              type: integer
        CIM_Processor:
          type: object
          properties:
            responses:
              type: array
              items:
                type: object
                properties:
                  cpuStatus:
                    type: integer
                  creationClassName:
                    type: string
                  currentClockSpeed:
                    type: integer
                  deviceID:
                    type: string
                  elementName:
                    type: string
                  enabledState:
                    type: integer
                  externalBusClockSpeed:
                    type: integer
                  family:
                    type: integer
                  healthState:
                    type: integer
                  maxClockSpeed:
                    type: integer
                  operationalStatus:
                    type: integer
                  requestedState:
                    type: integer
                  role:
                    type: string
                  stepping:
                    type: integer
                  systemCreationClassName:
                    type: string
                  systemName:
                    type: string
                  upgradeMethod:
                    type: integer
            status:
              type: integer
        CIM_PhysicalMemory:
          type: object
          properties:
            responses:
              type: array
              items:
                type: object
                properties:
                  bankLabel:
                    type: string
                  capacity:
                    type: integer
                  creationClassName:
                    type: string
                  elementName:
                    type: string
                  formFactor:
                    type: integer
                  manufacturer:
                    type: string
                  memoryType:
                    type: integer
                  partNumber:
                    type: string
                  serialNumber:
                    type: string
                  speed:
                    type: integer
                  tag:
                    type: integer
                    
            status:
              type: integer
              
        CIM_MediaAccessDevice:
          type: object
          properties:
            responses:
              type: array
              items:
                type: object
                properties:
                  capabilities:
                    type: array
                    items:
                        type: integer
                        
                  creationClassName:
                    type: string
                  deviceID:
                    type: string
                  elementName:
                    type: string
                  enabledDefault:
                    type: integer
                    
                  enabledState:
                    type: integer
                    
                  maxMediaSize:
                    type: integer
                    
                  operationalStatus:
                    type: integer
                    
                  requestedState:
                    type: integer
                    
                  security:
                    type: integer
                    
                  systemCreationClassName:
                    type: string
                  systemName:
                    type: string
            status:
              type: integer
              
        CIM_PhysicalPackage:
          type: object
          properties:
            responses:
              type: array
              items:
                type: object
                properties:
                  canBeFRUed:
                    type: boolean
                  creationClassName:
                    type: string
                  elementName:
                    type: string
                  manufacturer:
                    type: string
                  model:
                    type: string
                  operationalStatus:
                    type: integer
                    
                  packageType:
                    type: integer
                    
                  serialNumber:
                    type: string
                  tag:
                    type: string
                  version:
                    type: string
                  chassisPackageType:
                    type: integer
                    
            status:
              type: integer
                      
      example:
        CIM_ComputerSystemPackage:
          response:
            antecedent:
              address: http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous
              referenceParameters:
                resourceURI: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/  CIM_Chassis
                selectorSet:
                  selector:
                  - value: CIM_Chassis
                    "@name": CreationClassName
                  - value: CIM_Chassis
                    "@name": Tag
            dependent:
              address: http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous
              RreferenceParameters:
                resourceURI: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/  CIM_ComputerSystem
                selectorSet:
                  selector:
                  - value: CIM_ComputerSystem
                    "@name": CreationClassName
                  - value: ManagedSystem
                    "@name": Name
            platformGUID: 1095AC4BA6042143BAE2D45DDF07B684
          status: 200
        CIM_SystemPackaging:
          responses:
          - antecedent:
              address: http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous
              referenceParameters:
                resourceURI: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/  CIM_Chassis
                selectorSet:
                  selector:
                  - value: CIM_Chassis
                    "@name": CreationClassName
                  - value: CIM_Chassis
                    "@name": Tag
            dependent:
              address: http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous
              referenceParameters:
                resourceURI: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/  CIM_ComputerSystem
                selectorSet:
                  selector:
                  - value: CIM_ComputerSystem
                    "@name": CreationClassName
                  - value: ManagedSystem
                    "@name": Name
            platformGUID: 1095AC4BA6042143BAE2D45DDF07B684
          status: 200
        CIM_Chassis:
          response:
            chassisPackageType: 0
            creationClassName: CIM_Chassis
            elementName: Managed System Chassis
            manufacturer: Intel Corporation
            model: NUC7i5DNHE
            operationalStatus: 0
            packageType: 3
            serialNumber: DW1646647500075
            tag: CIM_Chassis
            version: J57828-503
          status: 200
        CIM_Chip:
          responses:
          - canBeFRUed: true
            creationClassName: CIM_Chip
            elementName: Managed System Processor Chip
            manufacturer: Intel(R) Corporation
            operationalStatus: 0
            tag: CPU 0
            version: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
          - bankLabel: BANK 0
            capacity: 4294967296
            creationClassName: CIM_PhysicalMemory
            elementName: Managed System Memory Chip
            formFactor: 13
            manufacturer: 04EF
            memoryType: 26
            partNumber: 'TEAMGROUP-SD4-2133  '
            serialNumber: 020300C5
            speed: 0
            tag: 9876543210
          - bankLabel: BANK 2
            capacity: 4294967296
            creationClassName: CIM_PhysicalMemory
            elementName: Managed System Memory Chip
            formFactor: 13
            manufacturer: 04EF
            memoryType: 26
            partNumber: 'TEAMGROUP-SD4-2133  '
            serialNumber: 020300BD
            speed: 0
            tag: 9876543210 (#2)
          status: 200
        CIM_Card:
          response:
            canBeFRUed: true
            creationClassName: CIM_Card
            elementName: Managed System Base Board
            manufacturer: Intel Corporation
            model: NUC7i5DNB
            operationalStatus: 0
            packageType: 9
            serialNumber: BTDN7490016E
            tag: CIM_Card
            version: J57626-503
          status: 200
        CIM_BIOSElement:
          response:
            elementName: Primary BIOS
            manufacturer: Intel Corp.
            name: Primary BIOS
            operationalStatus: 0
            primaryBIOS: true
            releaseDate:
              datetime: '2018-03-15T00:00:00Z'
            softwareElementID: DNKBLi5v.86A.0040.2018.0315.1451
            softwareElementState: 2
            targetOperatingSystem: 66
            version: DNKBLi5v.86A.0040.2018.0315.1451
          status: 200
        CIM_Processor:
          responses:
          - cpuStatus: 1
            creationClassName: CIM_Processor
            currentClockSpeed: 2500
            deviceID: CPU 0
            elementName: Managed System CPU
            enabledState: 2
            externalBusClockSpeed: 100
            family: 205
            healthState: 0
            maxClockSpeed: 8300
            operationalStatus: 0
            requestedState: 12
            role: Central
            stepping: 9
            systemCreationClassName: CIM_ComputerSystem
            systemName: ManagedSystem
            upgradeMethod: 2
          status: 200
        CIM_PhysicalMemory:
          responses:
          - bankLabel: BANK 0
            capacity: 4294967296
            creationClassName: CIM_PhysicalMemory
            elementName: Managed System Memory Chip
            formFactor: 13
            manufacturer: 04EF
            memoryType: 26
            partNumber: 'TEAMGROUP-SD4-2133  '
            serialNumber: 020300C5
            speed: 0
            tag: 9876543210
          - bankLabel: BANK 2
            capacity: 4294967296
            creationClassName: CIM_PhysicalMemory
            elementName: Managed System Memory Chip
            formFactor: 13
            manufacturer: 04EF
            memoryType: 26
            partNumber: 'TEAMGROUP-SD4-2133  '
            serialNumber: 020300BD
            speed: 0
            tag: 9876543210 (#2)
          status: 200
        CIM_MediaAccessDevice:
          responses:
          - capabilities:
            - 4
            - 10
            creationClassName: CIM_MediaAccessDevice
            deviceID: MEDIA DEV 0
            elementName: Managed System Media Access Device
            enabledDefault: 2
            enabledState: 0
            maxMediaSize: 250059350
            operationalStatus: 0
            requestedState: 12
            security: 2
            systemCreationClassName: CIM_ComputerSystem
            systemName: ManagedSystem
          status: 200
        CIM_PhysicalPackage:
          responses:
          - canBeFRUed: true
            creationClassName: CIM_Card
            elementName: Managed System Base Board
            manufacturer: Intel Corporation
            model: NUC7i5DNB
            operationalStatus: 0
            packageType: 9
            serialNumber: BTDN7490016E
            tag: CIM_Card
            version: J57626-503
          - creationClassName: CIM_PhysicalPackage
            elementName: Managed System Storage Media Package
            model: 'Samsung SSD 850 EVO M.2 250GB           '
            operationalStatus: 0
            packageType: 15
            serialNumber: 'S33CNX0JC36654D     '
            tag: Storage Media Package 0
          - chassisPackageType: 0
            creationClassName: CIM_Chassis
            elementName: Managed System Chassis
            manufacturer: Intel Corporation
            model: NUC7i5DNHE
            operationalStatus: 0
            packageType: 3
            serialNumber: DW1646647500075
            tag: CIM_Chassis
            version: J57828-503
          status: 200
    PowerActionRequest:
      title: PowerActionRequest
      example:
        action: 8
        useSOL: false
      properties:
        action:
          type: integer
          enum: 
            - 2
            - 5
            - 8
            - 10
            - 4
            - 7
            - 12
            - 14
            - 100
            - 101
            - 104
            - 200
            - 201
            - 202
            - 203
            - 300
            - 301
            - 400
            - 401
        useSOL:
          type: boolean
    PowerActionResponse:
      title: PowerActionResponse
      example:
        returnValue: 0
        returnValueStr: SUCCESS
      properties:
        returnValue:
          type: integer
        returnValueStr:
          type: string
    PowerCapabilitiesResponse:
      title: PowerCapabilitiesResponse
      properties:
        powerUp:
          type: integer
        powerCycle:
          type: integer
        powerDown:
          type: integer
        reset:
          type: integer
        softOff:
          type: integer
        softReset:
          type: integer
        sleep:
          type: integer
        hibernate:
          type: integer
        powerUpToBIOS:
          type: integer
        resetToBIOS:
          type: integer
        resetToSecureErase:
          type: integer
        resetToIDE-RFloppy:
          type: integer
        powerOnToIDE-RFloppy:
          type: integer
        resetToIDE-RCDROM:
          type: integer
        powerOnToIDE-RCDROM:
          type: integer
        resetToPXE:
          type: integer
        powerOnToPXE:
          type: integer
      example: 
        powerUp: 2
        powerCycle: 5
        powerDown: 8
        reset: 10
        softOff: 12
        softReset: 14
        sleep: 4
        hibernate: 7
        powerUpToBIOS: 100
        resetToBIOS: 101
        resetToSecureErase: 104
        resetToIDE-RFloppy: 200
        powerOnToIDE-RFloppy: 201
        resetToIDE-RCDROM: 202
        powerOnToIDE-RCDROM: 203
        resetToPXE: 400
        powerOnToPXE: 401
    PowerStateResponse:
      title: PowerStateResponse
      example:
        powerState: 2
      properties:
        powerState:
          type: integer
    SetAMTFeaturesResponse:
      type: string
      example: 
        status: 'Updated AMT Features'    
      properties:
        status:
          type: string
    VersionResponse:
      title: VersionResponse
      properties:
        CIM_SoftwareIdentity:
          type: object
          properties:
            responses:
              type: array
              items:
                type: object
                properties:
                  InstanceID:
                    type: string
                  IsEntity:
                    type: boolean
                  VersionString:
                    type: string
            status:
              type: integer
        AMT_SetupAndConfigurationService:
          type: object
          properties:
            response:
              type: object
              properties:
                CreationClassName:
                  type: string
                ElementName:
                  type: string
                EnabledState:
                  type: integer
                Name:
                  type: string
                PasswordModel:
                  type: integer
                ProvisioningMode:
                  type: integer
                ProvisioningServerOTP:
                  type: string
                ProvisioningState:
                  type: integer
                RequestedState:
                  type: integer
                SystemCreationClassName:
                  type: string
                SystemName:
                  type: string
                ZeroTouchConfigurationEnabled:
                  type: boolean
            responses:
              type: object
              properties:
                Header:
                  type: object
                  properties:
                    To:
                      type: string
                    RelatesTo:
                      type: string
                    Action:
                      type: string
                    MessageID:
                      type: string
                    ResourceURI:
                      type: string
                    Method:
                      type: string
                Body:
                  type: object
                  properties:
                    CreationClassName:
                      type: string
                    ElementName:
                      type: string
                    EnabledState:
                      type: integer
                    Name:
                      type: string
                    PasswordModel:
                      type: integer
                    ProvisioningMode:
                      type: integer
                    ProvisioningServerOTP:
                      type: string
                    ProvisioningState:
                      type: integer
                    RequestedState:
                      type: integer
                    SystemCreationClassName:
                      type: string
                    SystemName:
                      type: string
                    ZeroTouchConfigurationEnabled:
                      type: boolean
            status:
              type: integer
      example:
        CIM_SoftwareIdentity:
          responses:
          - instanceID: Flash
            isEntity: true
            versionString: 11.8.50
          - instanceID: Netstack
            isEntity: true
            versionString: 11.8.50
          - instanceID: AMTApps
            isEntity: true
            versionString: 11.8.50
          - instanceID: AMT
            isEntity: true
            versionString: 11.8.50
          - instanceID: Sku
            isEntity: true
            versionString: 16392
          - instanceID: VendorID
            isEntity: true
            versionString: 8086
          - instanceID: Build Number
            isEntity: true
            versionString: 3425
          - instanceID: Recovery Version
            isEntity: true
            versionString: 11.8.50
          - instanceID: Recovery Build Num
            isEntity: true
            versionString: 3425
          - instanceID: Legacy Mode
            isEntity: true
            versionString: 'False'
          - instanceID: AMT FW Core Version
            isEntity: true
            versionString: 11.8.50
          status: 200
        AMT_SetupAndConfigurationService:
          response:
            creationClassName: AMT_SetupAndConfigurationService
            elementName: Intel(r) AMT Setup and Configuration Service
            enabledState: 5
            name: Intel(r) AMT Setup and Configuration Service
            passwordModel: 1
            provisioningMode: 1
            provisioningServerOTP: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            provisioningState: 2
            requestedState: 12
            systemCreationClassName: CIM_ComputerSystem
            systemName: Intel(r) AMT
            zeroTouchConfigurationEnabled: true
          responses:
            Header:
                To: http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous
                RelatesTo: 3
                Action: http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse
                MessageID: uuid:00000000-8086-8086-8086-0000000006A4
                ResourceURI: http://intel.com/wbem/wscim/1/amt-schema/1/AMT_SetupAndConfigurationService
                Method: AMT_SetupAndConfigurationService
            Body:
                CreationClassName: AMT_SetupAndConfigurationService
                ElementName: Intel(r) AMT Setup and Configuration Service
                EnabledState: 5
                Name: Intel(r) AMT Setup and Configuration Service
                PasswordModel: 1
                ProvisioningMode: 1
                ProvisioningServerOTP: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
                ProvisioningState: 2
                RequestedState: 12
                SystemCreationClassName: CIM_ComputerSystem
                SystemName: Intel(r) AMT
                ZeroTouchConfigurationEnabled: true
          status: 200
    Device:
      title: Device
      example:
        guid: '123e4567-e89b-12d3-a456-426614174000'
        hostname: 'AMTDEVICENUC1'
        connectionStatus: 1
        tags: ['Texas','NUC','Store #123']
      properties:
        guid:
          type: string
        hostname:
          type: string
        connectionStatus:
          type: integer
        tags:
          type: array
          items:
            type: string
    AddDevice:
      title: AddDevice
      example:
        guid: '123e4567-e89b-12d3-a456-426614174000'
        hostname: 'AMTDEVICENUC1'
        tags: ['Texas','NUC','Store #123']
      properties:
        guid:
          type: string
        hostname:
          type: string
        tags:
          type: array
          items:
            type: string
    Stats:
      title: Stats
      example:
        totalCount: 1
        connectedCount: 1
        disconnectedCount: 0
      properties:
        totalCount:
          type: integer
        connectedCount:
          type: integer
        disconnectedCount:
          type: integer
    Metadata:
      title: Metadata
      required:
        - guid
        - tags
      type: object 
      example:
        guid: '123e4567-e89b-12d3-a456-426614174000'
        hostname: 'AMTDEVICENUC1'
        tags: ['Texas','NUC','Store #123']
      properties:
        guid:
          type: string
          description: The unique identifier for a given device
        hostname: 
          type: string
          description: The hostname of the device
        tags:
          type: array
          description: An Array of tags to associate to this device. Can be an empty array
          items:
            type: string